declare const _default: {
    arrowParens: string;
    bracketSameLine: boolean;
    bracketSpacing: boolean;
    embeddedLanguageFormatting: string;
    htmlWhitespaceSensitivity: string;
    insertPragma: boolean;
    jsxSingleQuote: boolean;
    printWidth: number;
    proseWrap: string;
    quoteProps: string;
    requirePragma: boolean;
    semi: boolean;
    singleAttributePerLine: boolean;
    singleQuote: boolean;
    tabWidth: number;
    trailingComma: string;
    useTabs: boolean;
    vueIndentScriptAndStyle: boolean;
};
export default _default;
